### ISSUE TITLE
Top Four

### ISSUE THREAD

**Issue by NSmonish** [IEEE-VIT/Howzat#11]
In the Standings tab add a new table that will have the same features as the existing table but it is for the top 4 qualifying nations.

**Comment by grlcodr** [comment]
Could I work on this, please? @NSmonish

**Comment by NSmonish** [comment]
> Could I work on this, please? @NSmonish

Yes you can work on this issue, I have assigned it to you. Make sure not to make any changes int the existing table of standings.

**Comment by abhi-shek-09** [comment]
Hey I have raised a PR could you look into it soon
Thank you!
