### ISSUE TITLE
Footer Updation

### ISSUE THREAD

**Issue by aadi101204** [IEEE-VIT/Howzat#3]
The footer of the home page(index.html) is not complete. In the footer (Follow us on Social), links to social media of the official ICC WC 23' are to be present. 
The links are already provided in index.html, the task is to get icons of respective social media and link them to the website.

**Comment by adarshpathak3408** [comment]
Please assign this issue to me with "Hacktober Fest" label

**Comment by Wafmulla** [comment]
Hello can you assign this issue to me with Hacktoberfest label?

**Comment by NSmonish** [comment]
> Please assign this issue to me with "Hacktober Fest" label

I have assigned the issue. You can start working on the footer.
