### ISSUE TITLE
Group Standings

### ISSUE THREAD

**Issue by aadi101204** [IEEE-VIT/Howzat#4]
When navigated to standings section of the page, a points table in this section contains 10 participating nations in alphabetic order. The task is to find a way to enable auto updation of the current standings after/during each fixture
Hint: Use API call or try Web Scrapping

**Comment by SilverDragonOfR** [comment]
Can you tell me what is "auto updation" ?
Like on refresh, it updates or there is a button for update or just updates every one hour or so ( last one looks inefficient imho )

**Comment by SilverDragonOfR** [comment]
@NSmonish @aadi101204 I have opened a PR for webscraping the official site on every reload. Please check it.
