### ISSUE TITLE
World Cup fixtures

### ISSUE THREAD

**Issue by aadi101204** [IEEE-VIT/Howzat#5]
Find the fixtures page which currently contains a sample container to hold the fixture details. 
Use the current styling or make it better.  The main task is to display all 48 fixtures of this world cup.
The table 'Fixtures' stored in the database must contain details on each fixture and this must displayed in the relevant HTML page

**Comment by SilverDragonOfR** [comment]
@aadi101204 I have made a PR for this issue, please check it.
