### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NSmonish** [IEEE-VIT/Howzat#8]
The ICC WC 23 logo in the home page looks dull, make it better by designing a new logo using any ui/ux software. 
Find the logo under the class “icclogo” in index.html.

**Comment by Ronit-gurjar** [comment]
Hey @NSmonish . i would like to work on it🔥pls assign to me

**Comment by NSmonish** [comment]
> Hey @NSmonish . i would like to work on it🔥pls assign to me

Ok I am assigning this issue to you, start working on it.
