### ISSUE TITLE
Represent the nation

### ISSUE THREAD

**Issue by NSmonish** [IEEE-VIT/Howzat#9]
The participating nations’ flags are missing or replaced in the Home page, make sure to identify and correct it along with better styling including the group's alignment.
Find it under class “team” in index.html and for styling use style.css.

**Comment by AvinashReddy19** [comment]
I can contribute to this @NSmonish

**Comment by NSmonish** [comment]
> I can contribute to this @NSmonish

Ok I am assigning this issue to you.

**Comment by NSmonish** [comment]
Ok I am assigning this issue to you to work on it.

**Comment by RonitBaranwal** [comment]
Is the issue resolved or else may I work on this one??
@AvinashReddy19  @NSmonish
